name: Build the application
on: 
  push: 
    branches: 
      - feature-*
  pull_request: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build the application
      run: echo running