name: Build the application
on: 
  push: 
    branches: 
      - feature-*
  pull_request: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: setup dotnet core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '6.0.x'
    - name: list current directory
      run: dotnet build
  notify:
    - name: send_notification
      uses: virajnemane31/ms-teams-new@v1.0
      with:
        webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        message: "This is from custom actions created"
