name: Build the application
on: 
  push: 
    branches: 
      - feature-*
  pull_request: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: list current directory
      run: | 
        pwd
        ls -ltr  