name: Build the application
on: 
  push: 
    branches: 
      - feature-*
  pull_request: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: setup dotnet core
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: '6.0.x'
    - name: list current directory
      run: dotnet build
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
    steps:
      - name: send notification
        uses: virajnemane31/ms-teams-new@v5.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}   
          message: "GitHub Action number ${{ github.run_number }} for ${{ github.repository }} triggered by ${{ github.actor }} is complted with ${{ needs.build.result }} status."